# Generated by Django 4.0.5 on 2022-07-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seguir_rename_comment_comentar_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguir',
            old_name='seqguindo',
            new_name='seguindo',
        ),
    ]
